### ISSUE TITLE
Rework Interface to have 6 dives in a row

### ISSUE THREAD

**Issue by gcalica** [TeamHookipa/divecomputer#16]
* Currently, our app only supports 8 dives. This is mainly a limitation of the front-end interface we're using, Semantic UI, which only supports <Grid>'s to only have up to 16 <Grid.Column>'s. 8 dives will take up 8 <Grid.Column>'s plus 7 <Grid.Column>'s for the Surface Interval Input Forms. Rework this such that we can have unlimited dives.
* If we aim to make unlimited dives, we don't want too many columns taking up one row because it's ugly. I think 6 dives in a row is a good compromise.

**Comment by jasonmaligon** [comment]
By making dives take up rows instead of columns, we can have an unlimited number of dives, and the space issue is fixed by having a vertically scrolling segment.
